defaults: &defaults
  - checkout
  - run: npm install
  - run: npm run test:ci
  - run: npm run cover:ci
  - store_artifacts:
      path: coverage
      prefix: coverage

version: 2.0
jobs:
  "node-10":
    docker:
      - image: circleci/node:10-browsers
    environment:
      - CODECLIMATE_REPO_TOKEN: c92188dcdeaca7d9732f8ea38fdd41d6bff18dc27a8d6f8b64a5b1311b7b6c21
    steps: *defaults
  "node-12":
    docker:
      - image: circleci/node:12-browsers
    environment:
      - CODECLIMATE_REPO_TOKEN: c92188dcdeaca7d9732f8ea38fdd41d6bff18dc27a8d6f8b64a5b1311b7b6c21
    steps: *defaults
  "node-14":
    docker:
      - image: circleci/node:14-browsers
    environment:
      - CODECLIMATE_REPO_TOKEN: c92188dcdeaca7d9732f8ea38fdd41d6bff18dc27a8d6f8b64a5b1311b7b6c21
    steps: *defaults

workflows:
  version: 2
  build:
    jobs:
      - "node-10"
      - "node-12"
      - "node-14"
